image: node:16.16.0

stages:
  - production

before_script:
  - npm install --global vercel

production:
  type: deploy
  stage: production
  script:
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
  only:
    - main
